# Generated by Django 3.2.8 on 2022-03-18 21:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(default='', max_length=100)),
                ('github_repository', models.CharField(default='', max_length=100)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('file', models.FileField(db_index=True, upload_to='')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=110)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Scanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('cms', models.CharField(default='', max_length=50)),
                ('webserver', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('ip', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], max_length=8)),
                ('message', models.CharField(blank=True, max_length=110)),
            ],
        ),
    ]
