# Generated by Django 3.2.8 on 2022-05-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_hunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='report_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanning',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='scan_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
